language: node_js
sudo: false
os:
  - linux
  - osx

node_js:
  - 11
  - 10
  - 8
  - 6.2.0

cache: npm

matrix:
  include:
    - node_js: 10
      env: HARMONY=true

before_install:
  - npm i -g npm

script:
 - |
      if [ $TRAVIS_NODE_VERSION = "6.2.0" ]
      then
        npm run test:prod
      else
        npm test
      fi
